---
title: "Loading data"
author: Antoine Andréoletti, Olivier Gaufrès, Amy Surry, Lea Skytthe, Trine Søgaard
format:
  html:
    embed-resources: true
editor: visual
---

# Data

The data we are using in this exercise comes from here: <https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/807/E-MTAB-12807/Files/>.

## Load Libraries

```{r}
#| message: False
#| warning: False

rm(list = ls())
library("tidyverse")
library("httr")
library("XML")
library("stringr")
```

## Creating data folder

```{r}
data_dir <- "../data"
raw_data_dir <- "../data/_raw/"
count_data_dir <- "../data/_raw/count_data"
metadata_dir <- "../data/_raw/metadata"

if( !dir.exists(data_dir) ){
  dir.create(path = data_dir)
}

if( !dir.exists(raw_data_dir) ){
  dir.create(path = raw_data_dir)
}

if( !dir.exists(count_data_dir) ){
  dir.create(path = count_data_dir)
}

if( !dir.exists(metadata_dir) ){
  dir.create(path = metadata_dir)
}
```

## Import data

```{r}
#| message: False
#| echo: False

base_url <- "https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/807/E-MTAB-12807/Files/"

# Make an HTTP GET request
response <- GET(base_url)

# Parse the HTML content
html_doc <- htmlParse(content(response, as = "text"), asText = TRUE)

# Extract file links (adjust the XPath as needed)
file_links <- xpathSApply(html_doc, "//a/@href")
file_links <- data.frame(files = file_links)

count_files <- file_links |> 
  filter(str_ends(files, ".sf")) |> 
  pull(files)

metadata_files <- file_links |> 
  filter(str_ends(files, ".txt")) |> 
  pull(files)

# Importing each file and downloading it in the right folder
base <- "../data/_raw"

# Downloading count data files
for (count_file in count_files) {
  new_file_name <- str_replace(count_file, "_quant.sf", "_quant.csv")
  new_file_path <- paste(base, "/count_data/", new_file_name,
                         sep = "")
  if (file.exists(new_file_path)) {
    next
  }
  file_path <- paste(base_url, count_file, 
                     sep = "")
  file <- read_tsv(file = file_path)
  write_csv(file, file = new_file_path)
}

# Downloading metadata files
for (metadata_file in metadata_files) {
  new_file_name <- str_replace(metadata_file, ".txt", ".csv")
  new_file_path <- paste(base, "/metadata/", new_file_name,
                         sep = "")
  if (file.exists(new_file_path)) {
    next
  }
  file_path <- paste(base_url, metadata_file, 
                     sep = "")
  file <- read_tsv(file = file_path)
  write_csv(file, file = new_file_path)
}
```
